### ISSUE TITLE
Languages + Open Source

### ISSUE THREAD

**Issue by saescapa** [SMHacks/website#3]
Refering to #2:
I understand it's nice to use other languages and such, but I highly prefer we keep it very basic with just HTML/CSS (SCSS) just because it's much easier (at a basic level) to read and easier to contribute. We want to keep all of our work open sourced (and documented [I know it's not]) so that anybody can use it and learn from it.

**Comment by molarmanful** [comment]
My 2 cents:
I use [Jade](http://jade-lang.com/) (an HTML extension) because it is much more readable and convenient to program with. It's also very, very easy to learn.

If this causes a problem, I'll just recompile with only HTML. However, I prefer that this doesn't happen.

 Documenting the source code can come later, _after_ we finish building the site.

We should get some other input from other people on the tech team.

EDIT:
Another option would be to create a `redesign` branch in master and redirect the pull request to that branch. I think that might work better in case you guys decide to ditch my approach.

**Comment by saescapa** [comment]
This has been solved correct? @cindyz8735 @molarmanful

**Comment by cindyz8735** [comment]
Yep since it's just Ben and me working on the website, we'll be using Jade.

**Comment by saescapa** [comment]
Awesome sounds goods
